diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
core.editor="C:\Users\SENA\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
user.email=ethiemalex03@gmail.com
user.name=EthiemGuerrero
credential.helper=store
filesystem.Oracle Corporation|1.8.0_191|-1038623696.timestampresolution=1001 microseconds
filesystem.Oracle Corporation|1.8.0_191|-1038623696.minracythreshold=0 nanoseconds
alias.lg=log --graph--oneline
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Epg33/vistas-proyecto
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
